version: "5"
services:
  back_bp:
    image: mongo:latest
    container_name: "bp_db"
    ports:
      - 27017:27017
    networks:
      back_network:
        ipv4_address: 172.20.0.10

  back_bp-api:
    image: back_bp-api:1.0
    container_name: "back_bp-api"
    ports:
      - 8080:8080

networks:
    back_network:
      ipam:
        driver: default
        config:
          - subnet: 172.20.0.0/16